# Male Vs Female Salary across different Job Titles
#### There are 129 different job titles in the dataset so I have summarised them to 5 different categories: Technology, Management, Marketing, Finance and Creative
#### Data contains: Mean, median, standard deviation, max, min and range

In [13]:
import pandas as pd
from tabulate import tabulate
salary_df = pd.read_csv("Salary.csv")
male_df = salary_df[salary_df.Gender == "Male"]
female_df = salary_df[salary_df.Gender =="Female"]

In [14]:
# Seeing if categories are needed for job titles!
diff_jobs_count = salary_df["Job Title"].nunique()
print(diff_jobs_count)  

diff_jobs = salary_df["Job Title"].unique()
# for job in diff_jobs:
#     print(job)

129

In [15]:
# Categories for job titles
technology_it = ["software", "engineer", "developer", "IT", "data"]
management_leadership = ["manager", "director", "CEO", "VP", "operations"]
marketing_communication = ["marketing", "analyst", "coordinator", "specialist", "digital"]
finance_analysis = ["financial", "analyst", "accountant", "advisor", "business intelligence"]
creative_design_content = ["designer", "creative", "content", "graphic", "UX"]

# Converting job titles to pandas series for regex usage
job_titles_series = pd.Series(diff_jobs)

# 5 Regex filters
filtered_technology = job_titles_series[job_titles_series.str.contains(r'\bsoftware\b|\bdeveloper\b|\bengineer\b|\bit|\bdata\b', case=False, regex=True)]
filtered_management = job_titles_series[job_titles_series.str.contains(r'\bmanager\b|\bdirector\b|\bceo\b|\bvp|\boperations\b', case=False, regex=True)]
filtered_marketing = job_titles_series[job_titles_series.str.contains(r'\bmarketing\b|\banalyst\b|\bcoordinator\b|\bspecialist|\bdigital\b', case=False, regex=True)]
filtered_finance = job_titles_series[job_titles_series.str.contains(r'\bfinancial\b|\banalyst\b|\baccountant\b|\badvisor|\bintelligence\b', case=False, regex=True)]
filtered_creative = job_titles_series[job_titles_series.str.contains(r'\bdesigner\b|\bcreative\b|\bcontent\b|\bgraphic|\bux\b', case=False, regex=True)]

print(filtered_technology.count(), filtered_management.count(), filtered_marketing.count(), filtered_finance.count(), filtered_creative.count())

other_jobs_count = 129 - 27 - 52 - 35 - 13 - 9
print(other_jobs_count, '\n') 

# Total counts for each category
filtered_technology_total = salary_df[salary_df["Job Title"].str.contains(r'\bsoftware\b|\bdeveloper\b|\bengineer\b|\bit|\bdata\b', case=False, regex=True)].Salary.count()
filtered_management_total = salary_df[salary_df["Job Title"].str.contains(r'\bmanager\b|\bdirector\b|\bceo\b|\bvp|\boperations\b', case=False, regex=True)].Salary.count()
filtered_marketing_total = salary_df[salary_df["Job Title"].str.contains(r'\bmarketing\b|\banalyst\b|\bcoordinator\b|\bspecialist|\bdigital\b', case=False, regex=True)].Salary.count()
filtered_finance_total = salary_df[salary_df["Job Title"].str.contains(r'\bfinancial\b|\banalyst\b|\baccountant\b|\badvisor|\bintelligence\b', case=False, regex=True)].Salary.count()
filtered_creative_total = salary_df[salary_df["Job Title"].str.contains(r'\bdesigner\b|\bcreative\b|\bcontent\b|\bgraphic|\bux\b', case=False, regex=True)].Salary.count()

print(filtered_technology_total, filtered_management_total, filtered_marketing_total, filtered_finance_total, filtered_creative_total)
#* Minimal overlap of roles, & relatively even count = overall good categorization of job titles

27 52 35 13 9
-7

3617 2217 1584 772 186

In [16]:
#* Creating new DF's (not series)
male_technology_df = male_df[male_df["Job Title"].str.contains(r'\bsoftware\b|\bdeveloper\b|\bengineer\b|\bit|\bdata\b', case=False, regex=True)]
male_management_df = male_df[male_df["Job Title"].str.contains(r'\bmanager\b|\bdirector\b|\bceo\b|\bvp|\boperations\b', case=False, regex=True)]
male_marketing_df = male_df[male_df["Job Title"].str.contains(r'\bmarketing\b|\banalyst\b|\bcoordinator\b|\bspecialist|\bdigital\b', case=False, regex=True)]
male_finance_df = male_df[male_df["Job Title"].str.contains(r'\bfinancial\b|\banalyst\b|\baccountant\b|\badvisor|\bintelligence\b', case=False, regex=True)]
male_creative_df = male_df[male_df["Job Title"].str.contains(r'\bdesigner\b|\bcreative\b|\bcontent\b|\bgraphic|\bux\b', case=False, regex=True)]

female_technology_df = female_df[female_df["Job Title"].str.contains(r'\bsoftware\b|\bdeveloper\b|\bengineer\b|\bit|\bdata\b', case=False, regex=True)]
female_management_df = female_df[female_df["Job Title"].str.contains(r'\bmanager\b|\bdirector\b|\bceo\b|\bvp|\boperations\b', case=False, regex=True)]
female_marketing_df = female_df[female_df["Job Title"].str.contains(r'\bmarketing\b|\banalyst\b|\bcoordinator\b|\bspecialist|\bdigital\b', case=False, regex=True)]
female_finance_df = female_df[female_df["Job Title"].str.contains(r'\bfinancial\b|\banalyst\b|\baccountant\b|\badvisor|\bintelligence\b', case=False, regex=True)]
female_creative_df = female_df[female_df["Job Title"].str.contains(r'\bdesigner\b|\bcreative\b|\bcontent\b|\bgraphic|\bux\b', case=False, regex=True)]

#! Mean
male_technology_mean = round(male_technology_df.Salary.mean(), 2)
male_management_mean = round(male_management_df.Salary.mean(), 2)
male_marketing_mean = round(male_marketing_df.Salary.mean(), 2)
male_finance_mean = round(male_finance_df.Salary.mean(), 2)
male_creative_mean = round(male_creative_df.Salary.mean(), 2)

female_technology_mean = round(female_technology_df.Salary.mean(), 2)
female_management_mean = round(female_management_df.Salary.mean(), 2)
female_marketing_mean = round(female_marketing_df.Salary.mean(), 2)
female_finance_mean = round(female_finance_df.Salary.mean(), 2)
female_creative_mean = round(female_creative_df.Salary.mean(), 2)

#! Median
male_technology_median = round(male_technology_df.Salary.median(), 2)
male_management_median = round(male_management_df.Salary.median(), 2)
male_marketing_median = round(male_marketing_df.Salary.median(), 2)
male_finance_median = round(male_finance_df.Salary.median(), 2)
male_creative_median = round(male_creative_df.Salary.median(), 2)

female_technology_median = round(female_technology_df.Salary.median(), 2)
female_management_median = round(female_management_df.Salary.median(), 2)
female_marketing_median = round(female_marketing_df.Salary.median(), 2)
female_finance_median = round(female_finance_df.Salary.median(), 2)
female_creative_median = round(female_creative_df.Salary.median(), 2)

#! Standard Deviation
male_technology_std = round(male_technology_df.Salary.std(), 2)
male_management_std = round(male_management_df.Salary.std(), 2)
male_marketing_std = round(male_marketing_df.Salary.std(), 2)
male_finance_std = round(male_finance_df.Salary.std(), 2)
male_creative_std = round(male_creative_df.Salary.std(), 2)

female_technology_std = round(female_technology_df.Salary.std(), 2)
female_management_std = round(female_management_df.Salary.std(), 2)
female_marketing_std = round(female_marketing_df.Salary.std(), 2)
female_finance_std = round(female_finance_df.Salary.std(), 2)
female_creative_std = round(female_creative_df.Salary.std(), 2)

#! Max
male_technology_max = round(male_technology_df.Salary.max(), 2)
male_management_max = round(male_management_df.Salary.max(), 2)
male_marketing_max = round(male_marketing_df.Salary.max(), 2)
male_finance_max = round(male_finance_df.Salary.max(), 2)
male_creative_max = round(male_creative_df.Salary.max(), 2)

female_technology_max = round(female_technology_df.Salary.max(), 2)
female_management_max = round(female_management_df.Salary.max(), 2)
female_marketing_max = round(female_marketing_df.Salary.max(), 2)
female_finance_max = round(female_finance_df.Salary.max(), 2)
female_creative_max = round(female_creative_df.Salary.max(), 2)

#! Min
male_technology_min = round(male_technology_df.Salary.min(), 2)
male_management_min = round(male_management_df.Salary.min(), 2)
male_marketing_min = round(male_marketing_df.Salary.min(), 2)
male_finance_min = round(male_finance_df.Salary.min(), 2)
male_creative_min = round(male_creative_df.Salary.min(), 2)

female_technology_min = round(female_technology_df.Salary.min(), 2)
female_management_min = round(female_management_df.Salary.min(), 2)
female_marketing_min = round(female_marketing_df.Salary.min(), 2)
female_finance_min = round(female_finance_df.Salary.min(), 2)
female_creative_min = round(female_creative_df.Salary.min(), 2)

#! Range
male_technology_diff = male_technology_max - male_technology_min
male_management_diff = male_management_max - male_management_min
male_marketing_diff = male_marketing_max - male_marketing_min
male_finance_diff = male_finance_max - male_finance_min
male_creative_diff = male_creative_max - male_creative_min

female_technology_diff = female_technology_max - female_technology_min
female_management_diff = female_management_max - female_management_min
female_marketing_diff = female_marketing_max - female_marketing_min
female_finance_diff = female_finance_max - female_finance_min
female_creative_diff = female_creative_max - female_creative_min

In [17]:
mean_table = [
    ["Technology", male_technology_mean, female_technology_mean],
    ["Management", male_management_mean, female_management_mean],
    ["Marketing", male_marketing_mean, female_marketing_mean],
    ["Finance", male_finance_mean, female_finance_mean],
    ["Creative", male_creative_mean, female_creative_mean]
]

median_table = [
    ["Technology", male_technology_median, female_technology_median],
    ["Management", male_management_median, female_management_median],
    ["Marketing", male_marketing_median, female_marketing_median],
    ["Finance", male_finance_median, female_finance_median],
    ["Creative", male_creative_median, female_creative_median]
]

std_table = [
    ["Technology", male_technology_std, female_technology_std],
    ["Management", male_management_std, female_management_std],
    ["Marketing", male_marketing_std, female_marketing_std],
    ["Finance", male_finance_std, female_finance_std],
    ["Creative", male_creative_std, female_creative_std]
]

min_table = [
    ["Technology", male_technology_min, female_technology_min],
    ["Management", male_management_min, female_management_min],
    ["Marketing", male_marketing_min, female_marketing_min],
    ["Finance", male_finance_min, female_finance_min],
    ["Creative", male_creative_min, female_creative_min]
]

max_table = [
    ["Technology", male_technology_max, female_technology_max],
    ["Management", male_management_max, female_management_max],
    ["Marketing", male_marketing_max, female_marketing_max],
    ["Finance", male_finance_max, female_finance_max],
    ["Creative", male_creative_max, female_creative_max]
]

diff_table = [
    ["Technology", male_technology_diff, female_technology_diff],
    ["Management", male_management_diff, female_management_diff],
    ["Marketing", male_marketing_diff, female_marketing_diff],
    ["Finance", male_finance_diff, female_finance_diff],
    ["Creative", male_creative_diff, female_creative_diff]
]

def table_creator(table_data):
    formatted_table_data = []
    headers_list = ["Job Type", "Male", "Female"]

    for row in table_data:
        formatted_row = []
        for value in row:
            if isinstance(value, (int, float)):
                formatted_value = f"{round(value):,.0f}"
            elif isinstance(value, str):
                formatted_value = value
            else:
                formatted_value = str(value)
            formatted_row.append(formatted_value)
        formatted_table_data.append(formatted_row)

    table = tabulate(formatted_table_data, headers_list, tablefmt="fancy_grid")
    return table

print("Mean Salary Table")
formatted_table = table_creator(mean_table)
print(formatted_table, '\n')

print("Median Salary Table")
formatted_table = table_creator(median_table)
print(formatted_table, '\n')

print("Standard Deviation Table")
formatted_table = table_creator(std_table)
print(formatted_table, '\n')

print("Maximum Salary Table")
formatted_table = table_creator(max_table)
print(formatted_table, '\n')

print("Minimum Salary Table")
formatted_table = table_creator(min_table)
print(formatted_table, '\n')

print("Salary Range Table")
formatted_table = table_creator(diff_table)
print(formatted_table, '\n')

Mean Salary Table
╒════════════╤═════════╤══════════╕
│ Job Type   │ Male    │ Female   │
╞════════════╪═════════╪══════════╡
│ Technology │ 134,320 │ 119,254  │
├────────────┼─────────┼──────────┤
│ Management │ 135,980 │ 133,556  │
├────────────┼─────────┼──────────┤
│ Marketing  │ 111,660 │ 98,360   │
├────────────┼─────────┼──────────┤
│ Finance    │ 104,517 │ 115,109  │
├────────────┼─────────┼──────────┤
│ Creative   │ 71,990  │ 104,157  │
╘════════════╧═════════╧══════════╛

Median Salary Table
╒════════════╤═════════╤══════════╕
│ Job Type   │ Male    │ Female   │
╞════════════╪═════════╪══════════╡
│ Technology │ 140,000 │ 120,000  │
├────────────┼─────────┼──────────┤
│ Management │ 135,000 │ 130,000  │
├────────────┼─────────┼──────────┤
│ Marketing  │ 100,000 │ 95,000   │
├────────────┼─────────┼──────────┤
│ Finance    │ 100,000 │ 110,000  │
├────────────┼─────────┼──────────┤
│ Creative   │ 55,000  │ 80,000   │
╘════════════╧═════════╧══════════╛

Standard Deviation Table
╒════════════╤════════╤══════════╕
│ Job Type   │ Male   │ Female   │
╞════════════╪════════╪══════════╡
│ Technology │ 49,171 │ 48,640   │
├────────────┼────────┼──────────┤
│ Management │ 48,104 │ 46,803   │
├────────────┼────────┼──────────┤
│ Marketing  │ 48,841 │ 39,258   │
├────────────┼────────┼──────────┤
│ Finance    │ 43,198 │ 48,679   │
├────────────┼────────┼──────────┤
│ Creative   │ 31,641 │ 52,943   │
╘════════════╧════════╧══════════╛

Maximum Salary Table
╒════════════╤═════════╤══════════╕
│ Job Type   │ Male    │ Female   │
╞════════════╪═════════╪══════════╡
│ Technology │ 240,000 │ 220,000  │
├────────────┼─────────┼──────────┤
│ Management │ 250,000 │ 220,000  │
├────────────┼─────────┼──────────┤
│ Marketing  │ 228,000 │ 200,000  │
├────────────┼─────────┼──────────┤
│ Finance    │ 250,000 │ 215,000  │
├────────────┼─────────┼──────────┤
│ Creative   │ 160,000 │ 190,000  │
╘════════════╧═════════╧══════════╛

Minimum Salary Table
╒════════════╤════════╤══════════╕
│ Job Type   │ Male   │ Female   │
╞════════════╪════════╪══════════╡
│ Technology │ 579    │ 550      │
├────────────┼────────┼──────────┤
│ Management │ 350    │ 35,000   │
├────────────┼────────┼──────────┤
│ Marketing  │ 350    │ 500      │
├────────────┼────────┼──────────┤
│ Finance    │ 350    │ 35,000   │
├────────────┼────────┼──────────┤
│ Creative   │ 45,000 │ 40,000   │
╘════════════╧════════╧══════════╛

Salary Range Table
╒════════════╤═════════╤══════════╕
│ Job Type   │ Male    │ Female   │
╞════════════╪═════════╪══════════╡
│ Technology │ 239,421 │ 219,450  │
├────────────┼─────────┼──────────┤
│ Management │ 249,650 │ 185,000  │
├────────────┼─────────┼──────────┤
│ Marketing  │ 227,650 │ 199,500  │
├────────────┼─────────┼──────────┤
│ Finance    │ 249,650 │ 180,000  │
├────────────┼─────────┼──────────┤
│ Creative   │ 115,000 │ 150,000  │
╘════════════╧═════════╧══════════╛

## Findings across different Job Titles:
- The largest salary difference occurs in Technology roles when looking at mean/ median. 
- The largest salary difference (towards females in this case) occurs in Creative roles when looking at mean/ median.